# ---------------------------------------------------------------------------------------------------------------------
# Gitlab-CI
#   * https://docs.gitlab.com/ee/ci/yaml/
# ---------------------------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------------------------
# Global defaults
# ---------------------------------------------------------------------------------------------------------------------

default:
  image: artifactory.sick.com/dockerhub-remote/node:16-buster-slim

  before_script:
    - export
  tags:
    - k8s-webx

cache:
    paths:
        - node_modules/
# ---------------------------------------------------------------------------------------------------------------------
# Global stages
# ---------------------------------------------------------------------------------------------------------------------

stages:
  - test

# ---------------------------------------------------------------------------------------------------------------------
# Main pipeline flow
# ---------------------------------------------------------------------------------------------------------------------

saucelabs:
  stage: test
  script:
     - chmod -R a+x node_modules
     - npm install --loglevel verbose
     - npm run fix

